package drl;
    dialect "java"
import com.kairos.planner.vrp.taskplanning.model.*;
import com.kairos.planner.vrp.taskplanning.*;
import org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder;

global HardMediumSoftLongScoreHolder scoreHolder;

rule "Task eligibility"
salience 20
    when
        $task:Task(prevTaskOrShift!=null, $m:missingSkills , $m!=0);
    then
        if($m>0)
            scoreHolder.addHardConstraintMatch(kcontext,-$m*2);
        else
            scoreHolder.addSoftConstraintMatch(kcontext,$m<<4);
end
