package com.kairos.enums;

public enum AssetAttributeName {


    NAME, DESCRIPTION, HOSTINGLOCATION, MANAGINGDEPARTMENT, ASSETOWNER, STORAGEFORMATS, ORGSECURITYMEASURES, TECHNICALSECURITYMEASURES,
    PROCESSINGACTIVITY, HOSTINGPROVIDER, HOSTINGTYPE, DATADISPOSAL, ASSETTYPE, ASSETSUBTYPES, DATARETENTIONPERIOD, MINDATASUBJECTVOLUME, MAXDATASUBJECTVOLUME


}
