package com.kairos.enums;

public enum ProcessingActivityAttributeName {

NAME,DESCRIPTION,MANAGINGDEPARTMENT, PROCESSOWNER,PROCESSINGPURPOSES,DATASOURCES,
    TRANSFERMETHODS,ACCESSORPARTIES,PROCESSINGLEGALBASIS,RESPONSIBILITYTYPE,CONTROLLERCONTACTINFO
    ,DPOCONTACTINFO,JOINTCONTROLLERCONTACTINFO,MINDATASUBJECTVOLUME,MAXDATASUBJECTVOLUME,DATARETENTIONPERIOD

}
