package com.kairos.persistence.model.common;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by prabjot on 14/11/16.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class QueryResult implements Serializable {

    private static final long serialVersionUID = 8643856511450413061L;
    private String name;
    private long id;
    private List<QueryResult> children = new ArrayList<>();
    private boolean isAccessable = false;
    private String type;
    private boolean kairosHub;
    private boolean preKairos;
    private boolean isEnabled;
    private boolean isOneTimeSyncPerformed;

    private boolean isAutoGeneratedPerformed;

    public void setEnabled(boolean enabled) {
        isEnabled = enabled;
    }

    public boolean isEnabled() {

        return isEnabled;
    }

    public QueryResult(String name, long id, List<QueryResult> children) {
        this.name = name;
        this.id = id;
        this.children = children;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setId(long id) {
        this.id = id;
    }

    public void setChildren(List<QueryResult> children) {
        this.children = children;
    }

    public String getName() {
        return name;
    }

    public long getId() {
        return id;
    }

    public List<QueryResult> getChildren() {
        return children;
    }

    public boolean isAccessable() {
        return isAccessable;
    }

    public void setAccessable(boolean accessable) {

        isAccessable = accessable;
    }

    public QueryResult() {
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getType() {

        return type;
    }

    public boolean isKairosHub() {
        return kairosHub;
    }

    public void setKairosHub(boolean kairosHub) {
        this.kairosHub = kairosHub;
    }

    public boolean isPreKairos() {
        return preKairos;
    }

    public void setPreKairos(boolean preKairos) {
        this.preKairos = preKairos;
    }

    public static QueryResult getInstance(){

        return new QueryResult();
    }

    public boolean isOneTimeSyncPerformed() {
        return isOneTimeSyncPerformed;
    }

    public void setOneTimeSyncPerformed(boolean oneTimeSyncPerformed) {
        isOneTimeSyncPerformed = oneTimeSyncPerformed;
    }

    public boolean isAutoGeneratedPerformed() {
        return isAutoGeneratedPerformed;
    }

    public void setAutoGeneratedPerformed(boolean autoGeneratedPerformed) {
        isAutoGeneratedPerformed = autoGeneratedPerformed;
    }
}
