package com.kairos.shiftplanning.rules;
    dialect "java"
import com.kairos.shiftplanning.domain.*;
import com.kairos.shiftplanning.utils.ShiftPlanningUtility;
import java.util.ArrayList;
import org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder;
global HardMediumSoftLongScoreHolder scoreHolder;


/******WTA rules********/


rule "Maximum Average Scheduled Time"
salience 20
    when
        $emp:Employee()
        $shifts:ArrayList(size>0) from collect (ShiftRequestPhase(getInterval()!=null && employee.equals($emp)))
        $constraintsPenality: Integer(intValue>0) from ($emp.checkConstraints($shifts,11))
    then
        $emp.breakLevelConstraints(scoreHolder,kcontext,11,$constraintsPenality);
end





/******WTA rules Ends****/
