package com.kairos.shiftplanning.rules;
    dialect "java"
import com.kairos.shiftplanning.domain.*;
import com.kairos.shiftplanning.utils.ShiftPlanningUtility;
import java.util.ArrayList;
import org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder;
global HardMediumSoftLongScoreHolder scoreHolder;


/******WTA rules********/

rule "Minimum Daily Resting Time"
salience 20
    when
       $emp:Employee()
        $shifts:ArrayList(size>0) from collect (ShiftRequestPhase(!isAbsenceActivityApplied() && getInterval()!=null && employee.equals($emp)))
        $constraintsPenality: Integer(intValue>0) from ($emp.checkConstraints($shifts,15))
    then
        $emp.breakLevelConstraints(scoreHolder,kcontext,15,$constraintsPenality);
end

/******WTA rules Ends****/
