package com.kairos.enums.shift;

public enum GeneralCoverShiftCriteria {
    INVITATIONS_CAN_A_STAFF_HAVE_AT_A_SAME_TIME,
    DAYS_BEFORE_START_OF_SHIFT_DOES_A_COVER_REQUEST_EXPIRE,
    PLANNER_APPROVAL_WEEKDAYS_BEFORE_START_DOES_A_COVER_REQUEST_EXPIRE,
    NOTIFICATIONS_TO_PLANNERS_IF_COVER_SHIFT_IS_ABOUT_TO_EXPIRE,
    DAYS_BEFORE_START_OF_SHIFT_CAN_A_COVER_REQUEST_BE_CREATED,
    WEEKDAYS_IN_ADVANCE_MUST_COVER_BE_CREATED,
    CANDIDATES_CAN_BE_INVITED_IN_SAME_BULK_PROCESS
}
