package drl;
    dialect "java"
import com.kairos.planner.vrp.taskplanning.model.*;
import com.kairos.planner.vrp.taskplanning.*;
import org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder;

global HardMediumSoftLongScoreHolder scoreHolder;
/********Task Rules*******/



rule "Unassigned Task"
salience 20
    when
        $task:Task(shift==null);
    then
        scoreHolder.addSoftConstraintMatch(kcontext,-1);
end


rule "Same road side tasks perference" // need to add check for one lane road
salience 22
    when
        Task(prevTaskOrShift instanceof Task  && getFullStreetName().equals(((Task)prevTaskOrShift).getFullStreetName()) && !areHouseNumberSameLane((Task)prevTaskOrShift))
    then
        scoreHolder.addSoftConstraintMatch(kcontext,-4);
end
