package drl;
    dialect "java"
import com.kairos.planner.vrp.taskplanning.model.*;
import com.kairos.planner.vrp.taskplanning.*;
import org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder;

global HardMediumSoftLongScoreHolder scoreHolder;


//breaks rules
rule "Full day shifts must have breaks"
salience 22
    when
        Shift(isFullWorkDay()  && $brks:expertiseId, $brks!=1)
    then
        scoreHolder.addHardConstraintMatch(kcontext,$brks==0?-1:-$brks);
end
