package com.kairos.shiftplanning.rules;
    dialect "java"
import com.kairos.shiftplanning.domain.activity.*;
import com.kairos.shiftplanningNewVersion.entity.*;
import com.kairos.shiftplanning.domain.staffing_level.*;
import com.kairos.shiftplanning.domain.skill.*;
import com.kairos.shiftplanning.utils.ShiftPlanningUtility;
import java.util.ArrayList;
import org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder;
global HardMediumSoftLongScoreHolder scoreHolder;
/********Activity Rules*******/
rule "Max Different Activity"
salience 20
    when
        $ac:Activity()
        $shift:Shift(!activityLineIntervals.isEmpty())
        $constraintsPenality: Integer(intValue>0) from ($ac.verifyConstraints($shift,ConstraintSubType.ACTIVITY_MUST_CONTINUOUS_NUMBER_OF_HOURS))
    then
        $ac.breakContraints(scoreHolder,kcontext,$constraintsPenality,ConstraintSubType.ACTIVITY_MUST_CONTINUOUS_NUMBER_OF_HOURS);
end
