package com.kairos.shiftplanning.rules;
    dialect "java"
import com.kairos.shiftplanning.domain.activity.*;
import com.kairos.shiftplanningNewVersion.entity.*;
import com.kairos.shiftplanning.domain.staffing_level.*;
import com.kairos.shiftplanning.domain.skill.*;
import com.kairos.enums.constraint.ConstraintSubType;
import com.kairos.shiftplanning.utils.ShiftPlanningUtility;
import java.util.ArrayList;
import org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder;
global HardMediumSoftLongScoreHolder scoreHolder;
/********Activity Rules*******/
rule "Max Shift of staff"
salience 20
    when
        $ac:Activity()
        $shift:Shift(!activityLineIntervals.isEmpty() && hasIntervalsForActivity($ac))
        $constraintsPenality: Integer(intValue>0) from ($ac.verifyConstraints($shift,ConstraintSubType.MAX_SHIFT_OF_STAFF))
    then
        $ac.breakContraints(scoreHolder,kcontext,$constraintsPenality,ConstraintSubType.MAX_SHIFT_OF_STAFF);
end