package com.kairos.shiftplanning.rules;
 dialect "java"

import com.kairos.shiftplanningNewVersion.entity.*;
import com.kairos.shiftplanning.domain.skill.*;
import com.kairos.shiftplanning.domain.unit.*;
import com.kairos.enums.constraint.ConstraintSubType;
import com.kairos.shiftplanning.utils.ShiftPlanningUtility;
import java.util.List;
import org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder;
global HardMediumSoftLongScoreHolder scoreHolder;


//We need to change it Unit
rule "Minimize Shift On Weekends"
salience 20
  when
    $ac:Activity()
    $shifts:List(size>0) from collect (Shift());
    $constraintsPenality: Integer(intValue>0) from ($ac.verifyConstraints($shifts,ConstraintSubType.MINIMIZE_SHIFT_ON_WEEKENDS))
  then
   $ac.breakContraints(scoreHolder,kcontext, $constraintsPenality,ConstraintSubType.MINIMIZE_SHIFT_ON_WEEKENDS);
end



