package com.kairos.shiftplanning.rules;
    dialect "java"
import com.kairos.shiftplanning.domain.activity.*;
import com.kairos.shiftplanningNewVersion.entity.*;
import com.kairos.shiftplanning.domain.staffing_level.*;
import com.kairos.shiftplanning.utils.ShiftPlanningUtility;
import java.util.ArrayList;
import org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder;
global HardMediumSoftLongScoreHolder scoreHolder;
/********Employee WTA Rules*******/
rule "Minimize Cost"
salience 20
    when
        $shift:Shift(!activityLineIntervals.isEmpty() && $staff:staff)
        $constraintsPenality: Integer(intValue>0) from ($staff.verifyConstraints(null,$shift,null,ConstraintSubType.MINIMIZE_COST))
    then
        $staff.breakContraints($shift,scoreHolder,kcontext,$constraintsPenality,ConstraintSubType.MINIMIZE_COST);
end
