package com.kairos.shiftplanning.rules;
    dialect "java"
import com.kairos.shiftplanning.domain.*;
import com.kairos.shiftplanning.utils.ShiftPlanningUtility;
import java.util.ArrayList;
import org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder;
global HardMediumSoftLongScoreHolder scoreHolder;



/********CTA rules*******/
rule "Shift Cost"
salience 20
    when
        $shift:ShiftRequestPhase(!activityLineIntervals.isEmpty())
        $shiftCost: Integer(intValue>0) from ($shift.getShiftCostInInt())
    then
        scoreHolder.addSoftConstraintMatch(kcontext,  - $shiftCost);
end

/*******CTA rules end****/
