package com.kairos.persistance.model.organization;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.google.common.base.Optional;
import com.google.common.collect.Lists;
import com.kairos.persistance.model.organization.enums.EnumString;
import com.kairos.persistance.model.organization.enums.OrganizationLevel;
import com.kairos.persistance.model.user.country.Country;
import jdk.nashorn.internal.objects.annotations.Property;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.validation.constraints.NotNull;
import java.time.ZoneId;
import java.util.*;


/**
 * organization domain & it's properties
 */
//@JsonSerialize(using = OrganizationSerializer.class)


@Document(collection = "organization")
public class Organization {




    @NotNull(message = "error.Organization.name.notnull")
    private String name;
    private String email;

    @Property(name = "organizationLevel")
    @EnumString(OrganizationLevel.class)
    private OrganizationLevel organizationLevel = OrganizationLevel.CITY;

    private String childLevel;

    private String eanNumber;
    @NotNull(message = "error.Organization.formal.notnull")
    private String formalName;
    private String costCenterCode;
    private String costCenterName;
    private String shortName;
    private String webSiteUrl;
    private Long clientSince;
    private String cvrNumber;
    private String pNumber;

    private boolean isKairosHub;
     private boolean isParentOrganization;
    private boolean isPrekairos;
    private boolean showPersonNames;
    private boolean isOneTimeSyncPerformed;

    private boolean isAutoGeneratedPerformed;

    public void setOneTimeSyncPerformed(boolean oneTimeSyncPerformed) {
        isOneTimeSyncPerformed = oneTimeSyncPerformed;
    }

    public boolean isOneTimeSyncPerformed() {

        return isOneTimeSyncPerformed;
    }
    // Relationships


    private Country country;


    private List<Organization> children = new ArrayList<>();

    private List<OrganizationType> organizationTypes;

    private List<OrganizationType> organizationSubTypes;

    private String description;
    private String externalId; //timeCare External Id
    private String estimoteAppId;
    private String estimoteAppToken;
    private int endTimeDeduction = 5; //in percentage

    private String kmdExternalId; //kmd External Id

    private int dayShiftTimeDeduction = 4; //in percentage

    private int nightShiftTimeDeduction = 7; //in percentage
    private boolean phaseGenerated = true;
    private Boolean showCountryTags = true;
    private boolean union;

    //set o.nightStartTimeFrom="22:15",o.nightEndTimeTo="07:15"

    public Organization() {
    }

    public boolean isUnion() {
        return union;
    }

    public void setUnion(boolean union) {
        this.union = union;
    }

     public Organization(String name) {
        this.name = name;
    }

    public String getDescription() {

        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getExternalId() {
        return externalId;
    }

    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

     public Country getCountry() {
        return country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

     public List<Organization> getChildren() {
        return children;

    }

    public void setChildren(List<Organization> children) {
        this.children = children;
    }

    public int getEndTimeDeduction() {
        return endTimeDeduction;
    }

    public void setEndTimeDeduction(int endTimeDeduction) {
        this.endTimeDeduction = endTimeDeduction;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getChildLevel() {
        return childLevel;
    }

    public void setChildLevel(String childLevel) {
        this.childLevel = childLevel;
    }

    public String getEstimoteAppId() {
        return estimoteAppId;
    }

    public void setEstimoteAppId(String estimoteAppId) {
        this.estimoteAppId = estimoteAppId;
    }

    public String getEstimoteAppToken() {
        return estimoteAppToken;
    }

    public void setEstimoteAppToken(String estimoteAppToken) {
        this.estimoteAppToken = estimoteAppToken;
    }

    public String getShortName() {
        return shortName;
    }

    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
public void setCostCenterName(String costCenterName) {
        this.costCenterName = costCenterName;
    }

    public void setWebSiteUrl(String webSiteUrl) {
        this.webSiteUrl = webSiteUrl;
    }

    public void setClientSince(Long clientSince) {
        this.clientSince = clientSince;
    }

    public String getCostCenterName() {
        return costCenterName;
    }

    public String getWebSiteUrl() {
        return webSiteUrl;
    }

    public Long getClientSince() {
        return clientSince;
    }


    public String getCvrNumber() {
        return cvrNumber;
    }

    public String getpNumber() {
        return pNumber;
    }

    public void setCvrNumber(String cvrNumber) {
        this.cvrNumber = cvrNumber;
    }

    public void setpNumber(String pNumber) {
        this.pNumber = pNumber;
    }

    public boolean isKairosHub() {
        return isKairosHub;
    }

    public void setKairosHub(boolean kairosHub) {
        isKairosHub = kairosHub;
    }

    public boolean isParentOrganization() {
        return isParentOrganization;
    }

    public void setParentOrganization(boolean parentOrganization) {
        isParentOrganization = parentOrganization;
    }

    public boolean isPrekairos() {
        return isPrekairos;
    }

    public void setPrekairos(boolean prekairos) {
        isPrekairos = prekairos;
    }

    public boolean isShowPersonNames() {
        return showPersonNames;
    }

    public void setShowPersonNames(boolean showPersonNames) {
        this.showPersonNames = showPersonNames;
    }

    public List<OrganizationType> getOrganizationTypes() {
        return Optional.fromNullable(organizationTypes).or(Lists.newArrayList());
    }

    public void setOrganizationTypes(List<OrganizationType> organizationTypes) {
        this.organizationTypes = organizationTypes;
    }

   public List<OrganizationType> getOrganizationSubTypes() {
        return Optional.fromNullable(organizationSubTypes).or(Lists.newArrayList());
    }

    public void setOrganizationSubTypes(List<OrganizationType> organizationSubTypes) {
        this.organizationSubTypes = organizationSubTypes;
    }

    public String getKmdExternalId() {
        return kmdExternalId;
    }

    public void setKmdExternalId(String kmdExternalId) {
        this.kmdExternalId = kmdExternalId;
    }

    public int getDayShiftTimeDeduction() {
        return dayShiftTimeDeduction;
    }

    public void setDayShiftTimeDeduction(int dayShiftTimeDeduction) {
        this.dayShiftTimeDeduction = dayShiftTimeDeduction;
    }

    public int getNightShiftTimeDeduction() {
        return nightShiftTimeDeduction;
    }

    public void setNightShiftTimeDeduction(int nightShiftTimeDeduction) {
        this.nightShiftTimeDeduction = nightShiftTimeDeduction;
    }

    public boolean isAutoGeneratedPerformed() {
        return isAutoGeneratedPerformed;
    }

    public void setAutoGeneratedPerformed(boolean autoGeneratedPerformed) {
        isAutoGeneratedPerformed = autoGeneratedPerformed;
    }

    public boolean isPhaseGenerated() {
        return phaseGenerated;
    }

    public void setPhaseGenerated(boolean phaseGenerated) {
        this.phaseGenerated = phaseGenerated;
    }


}

