package com.kairos.persistence.model.common;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.kairos.enums.OrganizationLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by prabjot on 14/11/16.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
@NoArgsConstructor
public class QueryResult {

    private String name;
    private long id;
    private List<QueryResult> children = new ArrayList<>();
    private List<QueryResult> units=new ArrayList<>();
    private boolean isAccessable = false;
    private String type;
    private boolean kairosHub;
    private boolean preKairos;
    private boolean isEnabled;
    private boolean isOneTimeSyncPerformed;
    private boolean isAutoGeneratedPerformed;
    private boolean isParentOrganization;
    private String timeZone;
    private Boolean union;
    private OrganizationLevel organizationLevel;
    private Long hubId;
    private boolean hasPermission;

    public QueryResult(String name, long id, List<QueryResult> children) {
        this.name = name;
        this.id = id;
        this.children = children;
    }

    public QueryResult(String name, long id, List<QueryResult> children, List<QueryResult> units, boolean isAccessable, boolean kairosHub,
                       boolean isEnabled, boolean isParentOrganization, String timeZone, Boolean union, Long hubId, boolean hasPermission) {
        this.name = name;
        this.id = id;
        this.children = children;
        this.units = units;
        this.isAccessable = isAccessable;
        this.kairosHub = kairosHub;
        this.isEnabled = isEnabled;
        this.isParentOrganization = isParentOrganization;
        this.timeZone = timeZone;
        this.union = union;
        this.hubId = hubId;
        this.hasPermission = hasPermission;
    }

    public static QueryResult getInstance(){
        return new QueryResult();
    }
}
