package com.kairos.persistence.model.common;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.kairos.enums.OrganizationLevel;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by prabjot on 14/11/16.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class QueryResult {

    private String name;
    private long id;
    private List<QueryResult> children = new ArrayList<>();
    private boolean isAccessable = false;
    private String type;
    private boolean kairosHub;
    private boolean preKairos;
    private boolean isEnabled;
    private boolean isOneTimeSyncPerformed;
    private boolean isAutoGeneratedPerformed;
    private boolean isParentOrganization;
    private String timeZone;
    private Boolean union;
    private OrganizationLevel organizationLevel;
    private Long hubId;

    public void setEnabled(boolean enabled) {
        isEnabled = enabled;
    }

    public boolean isEnabled() {

        return isEnabled;
    }

    public QueryResult(String name, long id, List<QueryResult> children) {
        this.name = name;
        this.id = id;
        this.children = children;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setId(long id) {
        this.id = id;
    }

    public void setChildren(List<QueryResult> children) {
        this.children = children;
    }

    public String getName() {
        return name;
    }

    public long getId() {
        return id;
    }

    public List<QueryResult> getChildren() {
        return children;
    }

    public boolean isAccessable() {
        return isAccessable;
    }

    public void setAccessable(boolean accessable) {

        isAccessable = accessable;
    }

    public QueryResult() {
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getType() {

        return type;
    }

    public boolean isKairosHub() {
        return kairosHub;
    }

    public void setKairosHub(boolean kairosHub) {
        this.kairosHub = kairosHub;
    }

    public boolean isPreKairos() {
        return preKairos;
    }

    public void setPreKairos(boolean preKairos) {
        this.preKairos = preKairos;
    }

    public static QueryResult getInstance(){

        return new QueryResult();
    }

    public boolean isOneTimeSyncPerformed() {
        return isOneTimeSyncPerformed;
    }

    public void setOneTimeSyncPerformed(boolean oneTimeSyncPerformed) {
        isOneTimeSyncPerformed = oneTimeSyncPerformed;
    }

    public boolean isAutoGeneratedPerformed() {
        return isAutoGeneratedPerformed;
    }

    public void setAutoGeneratedPerformed(boolean autoGeneratedPerformed) {
        isAutoGeneratedPerformed = autoGeneratedPerformed;
    }

    public boolean isParentOrganization() {
        return isParentOrganization;
    }

    public void setParentOrganization(boolean parentOrganization) {
        isParentOrganization = parentOrganization;
    }

    public String getTimeZone() {
        return timeZone;
    }

    public void setTimeZone(String timeZone) {
        this.timeZone = timeZone;
    }

    public Boolean getUnion() {
        return union;
    }

    public void setUnion(Boolean union) {
        this.union = union;
    }

    public OrganizationLevel getOrganizationLevel() {
        return organizationLevel;
    }

    public void setOrganizationLevel(OrganizationLevel organizationLevel) {
        this.organizationLevel = organizationLevel;
    }

    public Long getHubId() {
        return hubId;
    }

    public void setHubId(Long hubId) {
        this.hubId = hubId;
    }
}
