package com.kairos.persistence.model.common;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.kairos.dto.user.organization.CompanyType;
import com.kairos.enums.OrganizationLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by prabjot on 14/11/16.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
@NoArgsConstructor
public class QueryResult {

    private String name;
    private long id;
    private List<QueryResult> children = new ArrayList<>();
    private List<QueryResult> units=new ArrayList<>();
    private boolean isAccessable = false;
    private boolean kairosHub;
    private boolean preKairos;
    private boolean isEnabled;
    private boolean isOneTimeSyncPerformed;
    private boolean isAutoGeneratedPerformed;
    private String timeZone;
    private boolean union;
    private OrganizationLevel organizationLevel;
    private Long hubId;
    private boolean hasPermission;
    private boolean unit;
    private CompanyType type;

    public QueryResult(String name, long id, List<QueryResult> children) {
        this.name = name;
        this.id = id;
        this.children = children;
    }



    public static QueryResult getInstance(){
        return new QueryResult();
    }


}
