package com.kairos.constants;

/**
 * Constants for Application Usage
 */
public final class ApiConstants {

    public static final String API_V1 ="/api/v1";
    public static final String PARENT_ORGANIZATION_URL = "/organization/{organizationId}";
    public static final String UNIT_URL = "/unit/{unitId}";
    public static final String STAFF_URL = "/staff";
    public static final String ORGANIZATION_UNIT_URL = PARENT_ORGANIZATION_URL + UNIT_URL;
    public static final String COUNTRY_URL = "/country/{countryId}";
    public static final String API_ORGANIZATION_URL =  API_V1 + PARENT_ORGANIZATION_URL;
    public static final String API_ORGANIZATION_UNIT_URL = API_ORGANIZATION_URL + UNIT_URL;
    public static final String API_CONTROL_PANEL_SETTINGS_URL = "/control_panel/settings";
    public static final String API_CONTROL_PANEL_URL = API_ORGANIZATION_URL + UNIT_URL + API_CONTROL_PANEL_SETTINGS_URL;
    public static final String API_ABSENCE_PLANNING_URL = API_ORGANIZATION_URL + UNIT_URL + "/absence_planning";
    public static final String API_INTEGRATION_URL = API_ORGANIZATION_URL + UNIT_URL + "/integration";
    public static final String API_NOTIFICATION_URL = API_ORGANIZATION_URL  + "/notification";
    public static final String WS_URL="ws://localhost:8090"+API_V1+"/kairos/ws";
    public static final String API_REQUEST_COMPONENT_URL =  API_V1 + PARENT_ORGANIZATION_URL + "/resourceComponent";
    public static final String API_ORGANIZATION_COUNTRY_URL =API_V1+PARENT_ORGANIZATION_URL+COUNTRY_URL;
    public static final String TIMEBANK_URL = API_ORGANIZATION_UNIT_URL+"/timeBank";
    public static final String PAYOUT_URL = API_ORGANIZATION_UNIT_URL+"/payOut";
    public static final String COUNTER_DIST_URL = "/counter/dist";
    public static final String COUNTER_COUNTRY_DIST_URL=COUNTRY_URL+COUNTER_DIST_URL;
    public static final String COUNTER_UNIT_DIST_URL = UNIT_URL+COUNTER_DIST_URL;
    public static final String COUNTER_STAFF_UNIT_DIST_URL = UNIT_URL+STAFF_URL+COUNTER_DIST_URL;
    public static final String COUNTER_CONF_URL = "/counter/conf";
    public static final String COUNTER_DATA_URL = API_ORGANIZATION_UNIT_URL+"/counters/data";
    public static final String ORDER_URL = API_V1 + PARENT_ORGANIZATION_URL + UNIT_URL + "/orders";
    public static final String OPEN_SHIFT_URL = API_V1 + PARENT_ORGANIZATION_URL + UNIT_URL + "/open_shift";
    public static final String COUNTRY_ACTIVITY_CONFIGURATION=COUNTRY_URL+"/activity_configuration";
    public static final String UNIT_ACTIVITY_CONFIGURATION=UNIT_URL+"/activity_configuration";
    public static final String ACTIVITY_SHIFT_STATUS_SETTINGS_URL =UNIT_URL+"/activity_shift_status_settings";
    public static final String DASHBOARD_URL="/dashboard_tab";
    public static final String COUNTERS="/counters";
    public static final String CATEGORY="/category";
    public static final String TAB="/tab";
    public static final String ACCESS_GROUP="/access_group";
    public static final String ORG_TYPE="/org_type";
    //RestClientURL
    public static final String CTA_BASIC_INFO = "/cta_basic_info";
    public static final String GET_UNIT_POSITION = "/unit_position/{unitPositionId}";
    public static final String GET_REASONCODE = "/reason_codes";
    public static final String REMOVE_FUNCTIONS_BY_UNIT_POSITION_ID = "/unit_position/{unitPositionId}/remove_functions";
    public static final String RESTORE_FUNCTIONS_BY_UNIT_POSITION_ID = "/unit_position/{unitPositionId}/restore_functions";
    public static final String APPLY_FUNCTIONS_BY_UNIT_POSITION_ID = "/unit_position/{unitPositionId}/applyFunction";
    public static final String STAFF_USER_ACCESS_GROUP ="/staff/user/accessgroup";
    public static final String USER_STAFF_ID ="/user/staffId";
    public static final String STAFF_DETAILS ="/staff/details";
    public static final String ACCESS_GROUP_STAFFS ="/access_group/staffs";
    public static final String ORGANIZATION_TYPE_GET_ORGANIZATION_IDS ="/orgtype/get_organization_ids";
    public static final String KPI_DETAILS ="/kpi_details";
    public static final String UNIT_PARENT_ORGANIZATION_AND_COUNTRY ="/unit/parent_org_and_country";
    public static final String USER_USERID_STAFFS ="/user/{userId}/staffs";
    public static final String DAY_TYPES_AND_EMPLOYEMENT_TYPES ="/day_types_and_employment_types";
    public static final String STAFF_ACCESS_ROLES ="/staff/access_roles";
    public static final String STAFF_AND_UNIT_POSITIONS_BY_EXPERTISE_ID ="/expertise/{expertiseId}/staff_and_unit_positions";
    public static final String STAFF_EMAILS ="/staff/emails";
    public static final String UNIT_POSITIONS_BY_EXPERTISE_ID ="/expertise/{expertiseId}/unitPositions";
    public static final String EMPLOYEMENT_TYPE_AND_EXPERTISE ="/employment_type_and_expertise";
    public static final String STAFF_ACCESS_GROUPS ="/staff/access_groups";
    public static final String USER_WITH_ID_UNIT_SICK_SETTINGS ="/user/{userId}/unit_sick_settings";
    public static final String SICK_SETTINGS_DEFAULT ="/sick_settings/default";
    public static final String STAFFS_ACCESS_GROUPS ="/staffs/access_groups";
    public static final String COUNTRY_ID ="/countryId";
    public static final String STAFF_ID_EXPERTISE_ID_UNIT_POSITION_ID ="/staff/{staffId}/expertise/{expertiseId}/unitPositionId";
    public static final String ACCESS_GROUPS_BY_PARENT = "/access_groups_by_parent";
    public static final String STAFF_PRIORTY_GROUP ="/staff/priority_group";
    public static final String ABSENCE_TYPES_TITLE=" /absenceTypes/{title}";
    public static final String CONTRACT_TYPE="/contractType";
    public static final String COUNTRY_ORGANIZATION_SERVICE_URL="/country/organizaton_service/{organizationServiceId}";
    public static final String ORGANIZATION_TYPES_HIERARCHY="/organization_types/hierarchy";
    public static final String TASK_TYPES_SKILLS="/task_type/skills";
    public static final String TIME_SLOTS="/time_slots";
    public static final String DAY_TYPES="/day_types";
    public static final String INTEGRATION_UNIT_CITIZEN_UNIT_ID_FLSCRED="/integration/unit/{citizenUnitId}/flsCred";
    public static final String COUNTRY_COUNTRY_ID=COUNTRY_ID+"/{countryId}";
    public static final String SERVICE_DATA="/service/data";
    public static final String SKILLS ="/skills";
    public static final String STAFF_AND_SKILL="/staff/getsfAndsfSkill";
   public static final String STAFF_WITH_STAFF_ID="/staff/{staffId}";
    public static final String STAFF_UNIT_WISE="/staff/unitwise";
    public static final String UNIT_POSITION_EXPERTISE="/unit_position/expertise";
    public static final String STAFF_GET_STAFF_INFO="/staff/getStaffInfo";
    public static final String STAFF_GET_STAFF_BY_UNIT="/staff/get_Staff_By_Unit";
    public static final String UNIT_MANAGER_IDS_UNIT_ID="/unit_manager_ids/{unitId}";
    public static final String COUNTRY_ADMINS_IDS_OF_UNIT="/country_admins_ids/{countryAdminsOfUnitId}";
    public static final String VERIFY_UNIT_EMPLOYEMNT_BY_STAFF_ID=STAFF_WITH_STAFF_ID+"/verifyUnitEmployment";
    public static final String VERIFY_UNIT_EMPLOYEMNT_BY_STAFF_ID_UNIT_EMPLOYEMENT_ID=VERIFY_UNIT_EMPLOYEMNT_BY_STAFF_ID+"/{unitEmploymentId}";
    public static final String STAFF_CURRENT_USER_ID="/staff/current_user/{userId}";
    public static final String STAFF_GET_STAFF_BY_EXPERTISES="/staff/getStaffByExperties";
    public static final String CURRENT_USER_ACCESS_ROLE="/current_user/access_role";
    public static final String TIME_SLOT_URL="/time_slot/{timeSlotId}";
    public static final String CURRENT_TIME_SLOTS="/current/time_slots";
}
