
package de.tourenserver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VisiTour", targetNamespace = "http://www.tourenserver.de/", wsdlLocation = "file:/home/oodles/Desktop/FlsVisitour.wsdl")
public class VisiTour
    extends Service
{

    private final static URL VISITOUR_WSDL_LOCATION;
    private final static WebServiceException VISITOUR_EXCEPTION;
    private final static QName VISITOUR_QNAME = new QName("http://www.tourenserver.de/", "VisiTour");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/oodles/Desktop/FlsVisitour.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VISITOUR_WSDL_LOCATION = url;
        VISITOUR_EXCEPTION = e;
    }

    public VisiTour() {
        super(__getWsdlLocation(), VISITOUR_QNAME);
    }

    public VisiTour(WebServiceFeature... features) {
        super(__getWsdlLocation(), VISITOUR_QNAME, features);
    }

    public VisiTour(URL wsdlLocation) {
        super(wsdlLocation, VISITOUR_QNAME);
    }

    public VisiTour(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VISITOUR_QNAME, features);
    }

    public VisiTour(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VisiTour(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VisiTourSoap
     */
    @WebEndpoint(name = "VisiTourSoap")
    public VisiTourSoap getVisiTourSoap() {
        return super.getPort(new QName("http://www.tourenserver.de/", "VisiTourSoap"), VisiTourSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VisiTourSoap
     */
    @WebEndpoint(name = "VisiTourSoap")
    public VisiTourSoap getVisiTourSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.tourenserver.de/", "VisiTourSoap"), VisiTourSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VISITOUR_EXCEPTION!= null) {
            throw VISITOUR_EXCEPTION;
        }
        return VISITOUR_WSDL_LOCATION;
    }

}
