package com.kairos.shiftplanning.rules;
    dialect "java"
import com.kairos.shiftplanning.domain.*;
import com.kairos.shiftplanning.utils.ShiftPlanningUtility;
import java.util.ArrayList;
import org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder;
global HardMediumSoftLongScoreHolder scoreHolder;
/********Activity Rules*******/
rule "Min Length of Activity"
salience 20
    when
        $ac:Activity()
        $shift:ShiftRequestPhase(!activityLineIntervals.isEmpty() && hasIntervalsForActivity($ac))
        $constraintsPenality: Integer(intValue>0) from ($ac.checkActivityConstraints($shift,7))
    then
        $ac.breakActivityContraints(null,scoreHolder,kcontext,$constraintsPenality, 7);
end