package com.kairos.shiftplanning.rules;
    dialect "java"
import com.kairos.shiftplanning.domain.activity.*;
import com.kairos.shiftplanning.domain.shift.*;
import com.kairos.shiftplanning.domain.staffing_level.*;
import com.kairos.shiftplanning.domain.skill.*;
import com.kairos.shiftplanning.utils.ShiftPlanningUtility;
import java.util.ArrayList;
import org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder;
global HardMediumSoftLongScoreHolder scoreHolder;
/********Activity Rules*******/
rule "Max Different Activity"
salience 20
    when
        $ac:Activity()
        $shift:ShiftImp(!activityLineIntervals.isEmpty())
        $constraintsPenality: Integer(intValue>0) from ($ac.checkActivityConstraints($shift,4))
    then
        $ac.breakActivityContraints(null,scoreHolder,kcontext,$constraintsPenality,  4);
end
