package com.kairos.shiftplanning.rules;
    dialect "java"
import com.kairos.shiftplanning.domain.activity.*;
import com.kairos.shiftplanning.domain.shift.*;
import com.kairos.shiftplanning.domain.staffing_level.*;
import com.kairos.shiftplanning.domain.skill.*;
import com.kairos.enums.constraint.ConstraintSubType;
import com.kairos.shiftplanning.utils.ShiftPlanningUtility;
import java.util.ArrayList;
import org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder;
global HardMediumSoftLongScoreHolder scoreHolder;
/********Activity Rules*******/
rule "Max Allocation Per Shift"
salience 20
    when
        $ac:Activity()
        $shift:ShiftImp(!activityLineIntervals.isEmpty() && hasIntervalsForActivity($ac))
        $constraintsPenality: Integer(intValue>0) from ($ac.checkActivityConstraints($shift,ConstraintSubType.MAXIMUM_ALLOCATIONS_PER_SHIFT_FOR_THIS_ACTIVITY_PER_STAFF))
    then
        $ac.breakActivityContraints(null,scoreHolder,kcontext,$constraintsPenality,  ConstraintSubType.MAXIMUM_ALLOCATIONS_PER_SHIFT_FOR_THIS_ACTIVITY_PER_STAFF);
end
