package com.kairos.shiftplanning.rules;
 dialect "java"

import java.util.List;
import com.kairos.shiftplanning.domain.unit.Unit;
import com.kairos.shiftplanning.domain.shift.ShiftImp;
global HardMediumSoftLongScoreHolder scoreHolder;

rule "Minimize Shift On Weekends"
salience 20
  when
    $unit:Unit(constraints != null)
    $shifts:List() from collect (ShiftImp(getInterval()!=null));
    $constraintsPenality: Integer(intValue>0) from ($unit.checkConstraints(null,$shifts,ConstraintSubType.MINIMIZE_SHIFT_ON_WEEKENDS))
  then
   $unit.breakContraints(scoreHolder,kcontext, $constraintsPenality,ConstraintSubType.MINIMIZE_SHIFT_ON_WEEKENDS);
end

