package com.kairos.shiftplanning.rules;
 dialect "java"

import com.kairos.shiftplanning.domain.shift.*;
import com.kairos.shiftplanning.domain.skill.*;
import com.kairos.shiftplanning.domain.unit.*;
import com.kairos.enums.constraint.ConstraintSubType;
import com.kairos.shiftplanning.utils.ShiftPlanningUtility;
import java.util.List;
import org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder;
global HardMediumSoftLongScoreHolder scoreHolder;

rule "Minimize Shift On Weekends"
salience 20
  when
    $unit:Unit(constraints != null)
    $shifts:List(size>0) from collect (ShiftImp());
    $constraintsPenality: Integer(intValue>0) from ($unit.checkConstraints($shifts,ConstraintSubType.MINIMIZE_SHIFT_ON_WEEKENDS))
  then
   $unit.breakContraints(scoreHolder,kcontext, $constraintsPenality,ConstraintSubType.MINIMIZE_SHIFT_ON_WEEKENDS);
end

