package com.kairos.shiftplanning.rules;
 dialect "java"

import java.util.List;
import com.kairos.shiftplanning.domain.unit.Unit;
import com.kairos.shiftplanning.domain.shift.ShiftImp;
global HardMediumSoftLongScoreHolder scoreHolder;

rule "Prefer Permannent Employee"
salience 20
  when
    $unit:Unit(constraints != null)
    $shifts:List() from collect(ShiftImp(employee!=null))
    $constraintsPenality: Integer(intValue>0) from ($unit.checkConstraints(null,$shifts,ConstraintSubType.PREFER_PERMANENT_EMPLOYEE))
  then
   $unit.breakContraints(scoreHolder,kcontext, $constraintsPenality,ConstraintSubType.PREFER_PERMANENT_EMPLOYEE);
end