package com.kairos.shiftplanning.rules;
 dialect "java"

import java.util.List;
import com.kairos.shiftplanning.domain.unit.Unit;
import com.kairos.shiftplanning.domain.shift.ShiftImp;
global HardMediumSoftLongScoreHolder scoreHolder;

rule "Prefer Permannent Employee"
salience 20
  when
    $unit:Unit(unitConstraints != null)
    $shifts:List() from collect(ShiftImp(employee!=null))
    $constraintsPenality: Integer(intValue>0) from ($unit.checkConstraints($shifts,ConstraintSubType.MINIMIZE_SHIFT_ON_WEEKENDS))
  then
   $unit.breakContraints(scoreHolder,kcontext, $constraintsPenality,ConstraintSubType.MINIMIZE_SHIFT_ON_WEEKENDS);
end