package com.kairos.shiftplanning.rules;
    dialect "java"
import com.kairos.shiftplanning.domain.activity.*;
import com.kairos.shiftplanning.domain.shift.*;
import com.kairos.shiftplanning.domain.staffing_level.*;
import com.kairos.shiftplanning.domain.skill.*;
import com.kairos.shiftplanning.domain.staff.*;
import com.kairos.shiftplanning.domain.unit.*;
import com.kairos.enums.constraint.ConstraintSubType;
import com.kairos.shiftplanning.utils.ShiftPlanningUtility;
import java.util.List;
import org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder;

global HardMediumSoftLongScoreHolder scoreHolder;
/********Unit Rules*******/
rule "Presence Absence should not at same time"
salience 20
    when
        $unit:Unit(constraints != null)
        $emp:Employee()
        $shifts:List(size>0) from collect (ShiftImp(getInterval()!=null && employee.equals($emp)))
        $constraintsPenality: Integer(intValue>0) from ($unit.checkConstraints($shifts,ConstraintSubType.PRESENCE_AND_ABSENCE_SAME_TIME))
    then
        $unit.breakContraints(scoreHolder,kcontext,$constraintsPenality, ConstraintSubType.PRESENCE_AND_ABSENCE_SAME_TIME);
end