package com.kairos.enums.scheduler;

public enum JobSubType {

    INTEGRATION, EMPLOYMENT_END, PRIORITYGROUP_FILTER, QUESTIONAIRE_NIGHTWORKER, SENIORITY_LEVEL,USER_SICK, UPDATE_USER_ABSENCE, FLIP_PHASE,SHIFT_REMINDER


}