package com.kairos.enums.scheduler;

public enum JobSubType {

    INTEGRATION, EMPLOYMENT_END, PRIORITYGROUP_FILTER, QUESTIONAIRE_NIGHTWORKER, SENIORITY_LEVEL,USER_SICK, UPDATE_USER_ABSENCE, FLIP_PHASE,SHIFT_REMINDER,ATTENDANCE_SETTING,
    ADD_PLANNING_PERIOD,ADD_PAYROLL_PERIOD,UNASSIGN_EXPERTISE_FROM_ACTIVITY,NIGHT_WORKER,PROTECTED_DAYS_OFF,WTA_LEAVE_COUNT,ACTIVITY_CUTOFF



}