
package de.tourenserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VisiTourSoap", targetNamespace = "http://www.tourenserver.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VisiTourSoap {


    /**
     * 
     * @param zip
     * @param country
     * @param functionCode
     * @param nr
     * @param color
     * @param city
     * @param type
     * @param hNr
     * @param duration
     * @param fmId
     * @param fmExtId
     * @param street
     * @param district
     * @param x
     * @param y
     * @param id
     * @param text
     * @param begin
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Breaks", action = "http://localhost:80/VTS/WS/Breaks")
    @WebResult(name = "BreakResult", targetNamespace = "http://www.tourenserver.de/")
    @RequestWrapper(localName = "Breaks", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.Breaks")
    @ResponseWrapper(localName = "BreakResponse", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.BreakResponse")
    public int breaks(
        @WebParam(name = "FunctionCode", targetNamespace = "http://www.tourenserver.de/")
        int functionCode,
        @WebParam(name = "Nr", targetNamespace = "http://www.tourenserver.de/")
        Integer nr,
        @WebParam(name = "ID", targetNamespace = "http://www.tourenserver.de/")
        String id,
        @WebParam(name = "Duration", targetNamespace = "http://www.tourenserver.de/")
        Integer duration,
        @WebParam(name = "Color", targetNamespace = "http://www.tourenserver.de/")
        String color,
        @WebParam(name = "Text", targetNamespace = "http://www.tourenserver.de/")
        String text,
        @WebParam(name = "Begin", targetNamespace = "http://www.tourenserver.de/")
        XMLGregorianCalendar begin,
        @WebParam(name = "Type", targetNamespace = "http://www.tourenserver.de/")
        Integer type,
        @WebParam(name = "FMId", targetNamespace = "http://www.tourenserver.de/")
        Integer fmId,
        @WebParam(name = "FMExtId", targetNamespace = "http://www.tourenserver.de/")
        String fmExtId,
        @WebParam(name = "Country", targetNamespace = "http://www.tourenserver.de/")
        String country,
        @WebParam(name = "ZIP", targetNamespace = "http://www.tourenserver.de/")
        String zip,
        @WebParam(name = "City", targetNamespace = "http://www.tourenserver.de/")
        String city,
        @WebParam(name = "District", targetNamespace = "http://www.tourenserver.de/")
        String district,
        @WebParam(name = "Street", targetNamespace = "http://www.tourenserver.de/")
        String street,
        @WebParam(name = "HNr", targetNamespace = "http://www.tourenserver.de/")
        String hNr,
        @WebParam(name = "x", targetNamespace = "http://www.tourenserver.de/")
        Integer x,
        @WebParam(name = "y", targetNamespace = "http://www.tourenserver.de/")
        Integer y);

    /**
     * 
     * @param timeAttribute
     * @param relationType
     * @param country
     * @param agent
     * @param functionCode
     * @param phone2
     * @param weekday
     * @param sequenceGroup
     * @param setupTime
     * @param secondaryVisit
     * @param phone1
     * @param skills
     * @param externalProcessing
     * @param postProcessing
     * @param teamID
     * @param maxCost
     * @param equipmentName
     * @param state
     * @param mandator
     * @param zip
     * @param appointments
     * @param standbyType
     * @param priority
     * @param dateFrom
     * @param timeFrom
     * @param userfield2
     * @param userfield1
     * @param preferredFieldmanagerID2
     * @param equipmentNr
     * @param district
     * @param fixedFieldManagerID
     * @param name
     * @param openingHours
     * @param extID
     * @param name2
     * @param preferredFieldmanagerID
     * @param callResult
     * @param extraPenalty
     * @param showCall
     * @param forbiddenFieldManagerID
     * @param timeTo
     * @param fixedDate
     * @param city
     * @param contactPerson
     * @param relationExtID
     * @param units
     * @param maxKm
     * @param title
     * @param allowedFieldmanagerIDs
     * @param hNr
     * @param duration
     * @param regionID
     * @param street
     * @param addresstype
     * @param email
     * @param infoText
     * @param callInfo1
     * @param callInfo2
     * @param maxDetour
     * @param interruptible
     * @param vtid
     * @param customerExtID
     * @param taskTypeID
     * @param servicetype
     * @param reservationtime
     * @param x
     * @param dateTo
     * @param delayPenalty
     * @param y
     * @param areaOfExpertiseID
     * @param preparationtime
     */
    @WebMethod(operationName = "Call", action = "http://localhost:80/VTS/WS/Call")
    @RequestWrapper(localName = "Call", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.Call")
    @ResponseWrapper(localName = "CallResponse", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.CallResponse")
    public void call(
        @WebParam(name = "FunctionCode", targetNamespace = "http://www.tourenserver.de/")
        int functionCode,
        @WebParam(name = "Mandator", targetNamespace = "http://www.tourenserver.de/")
        Integer mandator,
        @WebParam(name = "Agent", targetNamespace = "http://www.tourenserver.de/")
        String agent,
        @WebParam(name = "ExtID", targetNamespace = "http://www.tourenserver.de/")
        String extID,
        @WebParam(name = "VTID", targetNamespace = "http://www.tourenserver.de/", mode = WebParam.Mode.INOUT)
        Holder<Integer> vtid,
        @WebParam(name = "CustomerExtID", targetNamespace = "http://www.tourenserver.de/")
        String customerExtID,
        @WebParam(name = "Name", targetNamespace = "http://www.tourenserver.de/")
        String name,
        @WebParam(name = "Name2", targetNamespace = "http://www.tourenserver.de/")
        String name2,
        @WebParam(name = "Title", targetNamespace = "http://www.tourenserver.de/")
        String title,
        @WebParam(name = "ContactPerson", targetNamespace = "http://www.tourenserver.de/")
        String contactPerson,
        @WebParam(name = "Phone1", targetNamespace = "http://www.tourenserver.de/")
        String phone1,
        @WebParam(name = "Phone2", targetNamespace = "http://www.tourenserver.de/")
        String phone2,
        @WebParam(name = "Email", targetNamespace = "http://www.tourenserver.de/")
        String email,
        @WebParam(name = "CallInfo1", targetNamespace = "http://www.tourenserver.de/")
        String callInfo1,
        @WebParam(name = "CallInfo2", targetNamespace = "http://www.tourenserver.de/")
        String callInfo2,
        @WebParam(name = "Userfield1", targetNamespace = "http://www.tourenserver.de/")
        String userfield1,
        @WebParam(name = "Userfield2", targetNamespace = "http://www.tourenserver.de/")
        String userfield2,
        @WebParam(name = "Country", targetNamespace = "http://www.tourenserver.de/")
        String country,
        @WebParam(name = "ZIP", targetNamespace = "http://www.tourenserver.de/")
        String zip,
        @WebParam(name = "City", targetNamespace = "http://www.tourenserver.de/")
        String city,
        @WebParam(name = "District", targetNamespace = "http://www.tourenserver.de/")
        String district,
        @WebParam(name = "Street", targetNamespace = "http://www.tourenserver.de/")
        String street,
        @WebParam(name = "HNr", targetNamespace = "http://www.tourenserver.de/")
        String hNr,
        @WebParam(name = "x", targetNamespace = "http://www.tourenserver.de/")
        Integer x,
        @WebParam(name = "y", targetNamespace = "http://www.tourenserver.de/")
        Integer y,
        @WebParam(name = "RegionID", targetNamespace = "http://www.tourenserver.de/")
        String regionID,
        @WebParam(name = "AreaOfExpertiseID", targetNamespace = "http://www.tourenserver.de/")
        String areaOfExpertiseID,
        @WebParam(name = "TeamID", targetNamespace = "http://www.tourenserver.de/")
        String teamID,
        @WebParam(name = "TaskTypeID", targetNamespace = "http://www.tourenserver.de/")
        String taskTypeID,
        @WebParam(name = "Servicetype", targetNamespace = "http://www.tourenserver.de/")
        Integer servicetype,
        @WebParam(name = "Priority", targetNamespace = "http://www.tourenserver.de/")
        Integer priority,
        @WebParam(name = "FixedFieldManagerID", targetNamespace = "http://www.tourenserver.de/")
        String fixedFieldManagerID,
        @WebParam(name = "ForbiddenFieldManagerID", targetNamespace = "http://www.tourenserver.de/")
        String forbiddenFieldManagerID,
        @WebParam(name = "PreferredFieldmanagerID", targetNamespace = "http://www.tourenserver.de/")
        String preferredFieldmanagerID,
        @WebParam(name = "PreferredFieldmanagerID2", targetNamespace = "http://www.tourenserver.de/")
        String preferredFieldmanagerID2,
        @WebParam(name = "AllowedFieldmanagerIDs", targetNamespace = "http://www.tourenserver.de/")
        String allowedFieldmanagerIDs,
        @WebParam(name = "ExternalProcessing", targetNamespace = "http://www.tourenserver.de/")
        Integer externalProcessing,
        @WebParam(name = "Skills", targetNamespace = "http://www.tourenserver.de/")
        String skills,
        @WebParam(name = "Units", targetNamespace = "http://www.tourenserver.de/")
        Integer units,
        @WebParam(name = "DateFrom", targetNamespace = "http://www.tourenserver.de/")
        XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://www.tourenserver.de/")
        XMLGregorianCalendar dateTo,
        @WebParam(name = "TimeFrom", targetNamespace = "http://www.tourenserver.de/")
        XMLGregorianCalendar timeFrom,
        @WebParam(name = "TimeTo", targetNamespace = "http://www.tourenserver.de/")
        XMLGregorianCalendar timeTo,
        @WebParam(name = "OpeningHours", targetNamespace = "http://www.tourenserver.de/")
        String openingHours,
        @WebParam(name = "Weekday", targetNamespace = "http://www.tourenserver.de/")
        String weekday,
        @WebParam(name = "TimeAttribute", targetNamespace = "http://www.tourenserver.de/")
        String timeAttribute,
        @WebParam(name = "Duration", targetNamespace = "http://www.tourenserver.de/")
        Integer duration,
        @WebParam(name = "Preparationtime", targetNamespace = "http://www.tourenserver.de/")
        Integer preparationtime,
        @WebParam(name = "PostProcessing", targetNamespace = "http://www.tourenserver.de/")
        Integer postProcessing,
        @WebParam(name = "SetupTime", targetNamespace = "http://www.tourenserver.de/")
        Integer setupTime,
        @WebParam(name = "Addresstype", targetNamespace = "http://www.tourenserver.de/")
        Integer addresstype,
        @WebParam(name = "SequenceGroup", targetNamespace = "http://www.tourenserver.de/")
        Integer sequenceGroup,
        @WebParam(name = "ExtraPenalty", targetNamespace = "http://www.tourenserver.de/")
        Integer extraPenalty,
        @WebParam(name = "DelayPenalty", targetNamespace = "http://www.tourenserver.de/")
        Float delayPenalty,
        @WebParam(name = "FixedDate", targetNamespace = "http://www.tourenserver.de/")
        XMLGregorianCalendar fixedDate,
        @WebParam(name = "State", targetNamespace = "http://www.tourenserver.de/")
        Integer state,
        @WebParam(name = "MaxDetour", targetNamespace = "http://www.tourenserver.de/")
        Integer maxDetour,
        @WebParam(name = "Reservationtime", targetNamespace = "http://www.tourenserver.de/")
        Integer reservationtime,
        @WebParam(name = "ShowCall", targetNamespace = "http://www.tourenserver.de/")
        String showCall,
        @WebParam(name = "SecondaryVisit", targetNamespace = "http://www.tourenserver.de/")
        String secondaryVisit,
        @WebParam(name = "EquipmentNr", targetNamespace = "http://www.tourenserver.de/")
        String equipmentNr,
        @WebParam(name = "EquipmentName", targetNamespace = "http://www.tourenserver.de/")
        String equipmentName,
        @WebParam(name = "Relation_ExtID", targetNamespace = "http://www.tourenserver.de/")
        String relationExtID,
        @WebParam(name = "Relation_type", targetNamespace = "http://www.tourenserver.de/")
        int relationType,
        @WebParam(name = "StandbyType", targetNamespace = "http://www.tourenserver.de/")
        Integer standbyType,
        @WebParam(name = "Interruptible", targetNamespace = "http://www.tourenserver.de/")
        Integer interruptible,
        @WebParam(name = "MaxCost", targetNamespace = "http://www.tourenserver.de/")
        Integer maxCost,
        @WebParam(name = "MaxKm", targetNamespace = "http://www.tourenserver.de/")
        Integer maxKm,
        @WebParam(name = "CallResult", targetNamespace = "http://www.tourenserver.de/", mode = WebParam.Mode.OUT)
        Holder<Integer> callResult,
        @WebParam(name = "InfoText", targetNamespace = "http://www.tourenserver.de/", mode = WebParam.Mode.OUT)
        Holder<String> infoText,
        @WebParam(name = "Appointments", targetNamespace = "http://www.tourenserver.de/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfAppointment> appointments);

    /**
     * 
     * @param eDistrict
     * @param snid
     * @param eStreet
     * @param sCity
     * @param workPercent
     * @param type
     * @param costKm
     * @param capacity
     * @param sCountry
     * @param regionID
     * @param lSkills
     * @param teamID
     * @param eCountry
     * @param fax
     * @param email
     * @param eCity
     * @param info
     * @param fmvtid
     * @param sx
     * @param sy
     * @param fieldManagerResult
     * @param mobile
     * @param active
     * @param prename
     * @param enid
     * @param costCall
     * @param sDistrict
     * @param sStreet
     * @param costDay
     * @param ezip
     * @param ex
     * @param ey
     * @param fmExtID
     * @param phone
     * @param speedPercent
     * @param name
     * @param szip
     * @param areaOfExpertiseID
     * @param overtime
     * @param costHourOvertime
     * @param costHour
     */
    @WebMethod(operationName = "FieldManager", action = "http://localhost:80/VTS/WS/FieldManager")
    @RequestWrapper(localName = "FieldManager", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.FieldManager")
    @ResponseWrapper(localName = "FieldManagerResponse", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.FieldManagerResponse")
    public void fieldManager(
        @WebParam(name = "FMVTID", targetNamespace = "http://www.tourenserver.de/", mode = WebParam.Mode.INOUT)
        Holder<Integer> fmvtid,
        @WebParam(name = "FMExtID", targetNamespace = "http://www.tourenserver.de/")
        String fmExtID,
        @WebParam(name = "Type", targetNamespace = "http://www.tourenserver.de/")
        String type,
        @WebParam(name = "Active", targetNamespace = "http://www.tourenserver.de/")
        Boolean active,
        @WebParam(name = "Prename", targetNamespace = "http://www.tourenserver.de/")
        String prename,
        @WebParam(name = "Name", targetNamespace = "http://www.tourenserver.de/")
        String name,
        @WebParam(name = "RegionID", targetNamespace = "http://www.tourenserver.de/")
        String regionID,
        @WebParam(name = "AreaOfExpertiseID", targetNamespace = "http://www.tourenserver.de/")
        String areaOfExpertiseID,
        @WebParam(name = "TeamID", targetNamespace = "http://www.tourenserver.de/")
        String teamID,
        @WebParam(name = "SCountry", targetNamespace = "http://www.tourenserver.de/")
        String sCountry,
        @WebParam(name = "SZIP", targetNamespace = "http://www.tourenserver.de/")
        String szip,
        @WebParam(name = "SCity", targetNamespace = "http://www.tourenserver.de/")
        String sCity,
        @WebParam(name = "SDistrict", targetNamespace = "http://www.tourenserver.de/")
        String sDistrict,
        @WebParam(name = "SStreet", targetNamespace = "http://www.tourenserver.de/")
        String sStreet,
        @WebParam(name = "SX", targetNamespace = "http://www.tourenserver.de/", mode = WebParam.Mode.INOUT)
        Holder<Integer> sx,
        @WebParam(name = "SY", targetNamespace = "http://www.tourenserver.de/", mode = WebParam.Mode.INOUT)
        Holder<Integer> sy,
        @WebParam(name = "SNID", targetNamespace = "http://www.tourenserver.de/", mode = WebParam.Mode.INOUT)
        Holder<Integer> snid,
        @WebParam(name = "ECountry", targetNamespace = "http://www.tourenserver.de/")
        String eCountry,
        @WebParam(name = "EZIP", targetNamespace = "http://www.tourenserver.de/")
        String ezip,
        @WebParam(name = "ECity", targetNamespace = "http://www.tourenserver.de/")
        String eCity,
        @WebParam(name = "EDistrict", targetNamespace = "http://www.tourenserver.de/")
        String eDistrict,
        @WebParam(name = "EStreet", targetNamespace = "http://www.tourenserver.de/")
        String eStreet,
        @WebParam(name = "EX", targetNamespace = "http://www.tourenserver.de/", mode = WebParam.Mode.INOUT)
        Holder<Integer> ex,
        @WebParam(name = "EY", targetNamespace = "http://www.tourenserver.de/", mode = WebParam.Mode.INOUT)
        Holder<Integer> ey,
        @WebParam(name = "ENID", targetNamespace = "http://www.tourenserver.de/", mode = WebParam.Mode.INOUT)
        Holder<Integer> enid,
        @WebParam(name = "Info", targetNamespace = "http://www.tourenserver.de/")
        String info,
        @WebParam(name = "Email", targetNamespace = "http://www.tourenserver.de/")
        String email,
        @WebParam(name = "Phone", targetNamespace = "http://www.tourenserver.de/")
        String phone,
        @WebParam(name = "Mobile", targetNamespace = "http://www.tourenserver.de/")
        String mobile,
        @WebParam(name = "Fax", targetNamespace = "http://www.tourenserver.de/")
        String fax,
        @WebParam(name = "LSkills", targetNamespace = "http://www.tourenserver.de/")
        String lSkills,
        @WebParam(name = "Capacity", targetNamespace = "http://www.tourenserver.de/")
        Integer capacity,
        @WebParam(name = "SpeedPercent", targetNamespace = "http://www.tourenserver.de/")
        Integer speedPercent,
        @WebParam(name = "WorkPercent", targetNamespace = "http://www.tourenserver.de/")
        Integer workPercent,
        @WebParam(name = "Overtime", targetNamespace = "http://www.tourenserver.de/")
        Integer overtime,
        @WebParam(name = "CostDay", targetNamespace = "http://www.tourenserver.de/")
        Float costDay,
        @WebParam(name = "CostCall", targetNamespace = "http://www.tourenserver.de/")
        Float costCall,
        @WebParam(name = "CostKm", targetNamespace = "http://www.tourenserver.de/")
        Float costKm,
        @WebParam(name = "CostHour", targetNamespace = "http://www.tourenserver.de/")
        Float costHour,
        @WebParam(name = "CostHourOvertime", targetNamespace = "http://www.tourenserver.de/")
        Float costHourOvertime,
        @WebParam(name = "FieldManagerResult", targetNamespace = "http://www.tourenserver.de/", mode = WebParam.Mode.OUT)
        Holder<Integer> fieldManagerResult);

    /**
     * 
     * @param fixNextCalls
     * @param start
     * @param show
     * @param fixCalls
     * @param fixTime
     * @param showReturn
     * @param vtid
     * @param regionID
     * @param fmExtID
     * @param teamID
     * @param unconfirmCalls
     * @param areaOfExpertiseID
     * @param end
     * @param confirmCalls
     * @param extID
     * @param unFix
     * @return
     *     returns de.tourenserver.ArrayOfFixedCall
     */
    @WebMethod(operationName = "FixSchedule", action = "http://localhost:80/VTS/WS/FixSchedule")
    @WebResult(name = "FixScheduleResult", targetNamespace = "http://www.tourenserver.de/")
    @RequestWrapper(localName = "FixSchedule", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.FixSchedule")
    @ResponseWrapper(localName = "FixScheduleResponse", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.FixScheduleResponse")
    public ArrayOfFixedCall fixSchedule(
        @WebParam(name = "ExtID", targetNamespace = "http://www.tourenserver.de/")
        String extID,
        @WebParam(name = "VTID", targetNamespace = "http://www.tourenserver.de/")
        Integer vtid,
        @WebParam(name = "Start", targetNamespace = "http://www.tourenserver.de/")
        XMLGregorianCalendar start,
        @WebParam(name = "End", targetNamespace = "http://www.tourenserver.de/")
        XMLGregorianCalendar end,
        @WebParam(name = "RegionID", targetNamespace = "http://www.tourenserver.de/")
        String regionID,
        @WebParam(name = "TeamID", targetNamespace = "http://www.tourenserver.de/")
        String teamID,
        @WebParam(name = "AreaOfExpertiseID", targetNamespace = "http://www.tourenserver.de/")
        String areaOfExpertiseID,
        @WebParam(name = "FMExtID", targetNamespace = "http://www.tourenserver.de/")
        String fmExtID,
        @WebParam(name = "UnFix", targetNamespace = "http://www.tourenserver.de/")
        Boolean unFix,
        @WebParam(name = "ConfirmCalls", targetNamespace = "http://www.tourenserver.de/")
        Boolean confirmCalls,
        @WebParam(name = "UnconfirmCalls", targetNamespace = "http://www.tourenserver.de/")
        Boolean unconfirmCalls,
        @WebParam(name = "FixCalls", targetNamespace = "http://www.tourenserver.de/")
        Boolean fixCalls,
        @WebParam(name = "FixTime", targetNamespace = "http://www.tourenserver.de/")
        Boolean fixTime,
        @WebParam(name = "FixNextCalls", targetNamespace = "http://www.tourenserver.de/")
        Integer fixNextCalls,
        @WebParam(name = "Show", targetNamespace = "http://www.tourenserver.de/")
        Boolean show,
        @WebParam(name = "ShowReturn", targetNamespace = "http://www.tourenserver.de/")
        Boolean showReturn);

    /**
     * 
     * @param zip
     * @param country
     * @param city
     * @param street
     * @param district
     * @param hNr
     * @param fuzzy
     * @param callSimulation
     * @return
     *     returns de.tourenserver.ArrayOfGeoCodeRec
     */
    @WebMethod(operationName = "Geocode", action = "http://localhost:80/VTS/WS/Geocode")
    @WebResult(name = "GeocodeResult", targetNamespace = "http://www.tourenserver.de/")
    @RequestWrapper(localName = "Geocode", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.Geocode")
    @ResponseWrapper(localName = "GeocodeResponse", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.GeocodeResponse")
    public ArrayOfGeoCodeRec geocode(
        @WebParam(name = "Country", targetNamespace = "http://www.tourenserver.de/")
        String country,
        @WebParam(name = "ZIP", targetNamespace = "http://www.tourenserver.de/")
        String zip,
        @WebParam(name = "City", targetNamespace = "http://www.tourenserver.de/")
        String city,
        @WebParam(name = "District", targetNamespace = "http://www.tourenserver.de/")
        String district,
        @WebParam(name = "Street", targetNamespace = "http://www.tourenserver.de/")
        String street,
        @WebParam(name = "HNr", targetNamespace = "http://www.tourenserver.de/")
        String hNr,
        @WebParam(name = "Fuzzy", targetNamespace = "http://www.tourenserver.de/")
        Boolean fuzzy,
        @WebParam(name = "CallSimulation", targetNamespace = "http://www.tourenserver.de/")
        Boolean callSimulation);

    /**
     * 
     * @param mandator
     * @param callID
     * @param agent
     * @param scheduleNextCall
     * @param attachments
     * @param mobileMessageResult
     * @param sentCallVTIDs
     * @param trackPoints
     * @param vtid
     * @param timeStamp
     * @param duration
     * @param scheduleCalls
     * @param sentCallExtIDs
     * @param messageType
     * @param substate
     * @param fmExtID
     * @param nextCalls
     * @param newState
     * @param searchNextCall
     * @param info
     */
    @WebMethod(operationName = "MobileMessage", action = "http://localhost:80/VTS/WS/MobileMessage")
    @RequestWrapper(localName = "MobileMessage", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.MobileMessage")
    @ResponseWrapper(localName = "MobileMessageResponse", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.MobileMessageResponse")
    public void mobileMessage(
        @WebParam(name = "Mandator", targetNamespace = "http://www.tourenserver.de/")
        Integer mandator,
        @WebParam(name = "Agent", targetNamespace = "http://www.tourenserver.de/")
        String agent,
        @WebParam(name = "FMExtID", targetNamespace = "http://www.tourenserver.de/")
        String fmExtID,
        @WebParam(name = "TimeStamp", targetNamespace = "http://www.tourenserver.de/")
        XMLGregorianCalendar timeStamp,
        @WebParam(name = "MessageType", targetNamespace = "http://www.tourenserver.de/")
        int messageType,
        @WebParam(name = "VTID", targetNamespace = "http://www.tourenserver.de/")
        Integer vtid,
        @WebParam(name = "CallID", targetNamespace = "http://www.tourenserver.de/")
        String callID,
        @WebParam(name = "Duration", targetNamespace = "http://www.tourenserver.de/")
        Integer duration,
        @WebParam(name = "NewState", targetNamespace = "http://www.tourenserver.de/")
        Integer newState,
        @WebParam(name = "substate", targetNamespace = "http://www.tourenserver.de/")
        Integer substate,
        @WebParam(name = "Info", targetNamespace = "http://www.tourenserver.de/")
        String info,
        @WebParam(name = "SearchNextCall", targetNamespace = "http://www.tourenserver.de/")
        Boolean searchNextCall,
        @WebParam(name = "ScheduleNextCall", targetNamespace = "http://www.tourenserver.de/")
        Boolean scheduleNextCall,
        @WebParam(name = "ScheduleCalls", targetNamespace = "http://www.tourenserver.de/")
        Integer scheduleCalls,
        @WebParam(name = "SentCallExtIDs", targetNamespace = "http://www.tourenserver.de/")
        String sentCallExtIDs,
        @WebParam(name = "SentCallVTIDs", targetNamespace = "http://www.tourenserver.de/")
        String sentCallVTIDs,
        @WebParam(name = "Attachments", targetNamespace = "http://www.tourenserver.de/")
        ArrayOfAttachment attachments,
        @WebParam(name = "TrackPoints", targetNamespace = "http://www.tourenserver.de/")
        ArrayOfTrackPoint trackPoints,
        @WebParam(name = "MobileMessageResult", targetNamespace = "http://www.tourenserver.de/", mode = WebParam.Mode.OUT)
        Holder<Integer> mobileMessageResult,
        @WebParam(name = "NextCalls", targetNamespace = "http://www.tourenserver.de/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfNextCall> nextCalls);

    /**
     * 
     * @param mandator
     * @param endDate
     * @param fieldManagerExtIDs
     * @param computingTime
     * @param regionIDs
     * @param areaOfExpertiseIDs
     * @param utilisationRatio
     * @param startDate
     * @param teamIDs
     * @param openCallsMode
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Optimize", action = "http://localhost:80/VTS/WS/Optimize")
    @WebResult(name = "OptimizeResult", targetNamespace = "http://www.tourenserver.de/")
    @RequestWrapper(localName = "Optimize", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.Optimize")
    @ResponseWrapper(localName = "OptimizeResponse", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.OptimizeResponse")
    public int optimize(
        @WebParam(name = "Mandator", targetNamespace = "http://www.tourenserver.de/")
        Integer mandator,
        @WebParam(name = "StartDate", targetNamespace = "http://www.tourenserver.de/")
        XMLGregorianCalendar startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.tourenserver.de/")
        XMLGregorianCalendar endDate,
        @WebParam(name = "RegionIDs", targetNamespace = "http://www.tourenserver.de/")
        String regionIDs,
        @WebParam(name = "AreaOfExpertiseIDs", targetNamespace = "http://www.tourenserver.de/")
        String areaOfExpertiseIDs,
        @WebParam(name = "TeamIDs", targetNamespace = "http://www.tourenserver.de/")
        String teamIDs,
        @WebParam(name = "FieldManagerExtIDs", targetNamespace = "http://www.tourenserver.de/")
        String fieldManagerExtIDs,
        @WebParam(name = "UtilisationRatio", targetNamespace = "http://www.tourenserver.de/")
        Integer utilisationRatio,
        @WebParam(name = "OpenCallsMode", targetNamespace = "http://www.tourenserver.de/")
        Integer openCallsMode,
        @WebParam(name = "ComputingTime", targetNamespace = "http://www.tourenserver.de/")
        Integer computingTime);

    /**
     * 
     * @param extID
     * @param vtid
     * @return
     *     returns de.tourenserver.CallInfoRec
     */
    @WebMethod(operationName = "ShowCallInfo", action = "http://localhost:80/VTS/WS/ShowCallInfo")
    @WebResult(name = "ShowCallInfoResult", targetNamespace = "http://www.tourenserver.de/")
    @RequestWrapper(localName = "ShowCallInfo", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.ShowCallInfo")
    @ResponseWrapper(localName = "ShowCallInfoResponse", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.ShowCallInfoResponse")
    public CallInfoRec showCallInfo(
        @WebParam(name = "VTID", targetNamespace = "http://www.tourenserver.de/")
        Integer vtid,
        @WebParam(name = "ExtID", targetNamespace = "http://www.tourenserver.de/")
        String extID);

    /**
     * 
     * @param sbType
     * @param fmvtid
     * @param endDate
     * @param shift
     * @param type
     * @param replanning
     * @param startLocation
     * @param fmExtID
     * @param days
     * @param startTime
     * @param endTime
     * @param startDate
     * @param endLocation
     * @param info
     * @return
     *     returns int
     */
    @WebMethod(operationName = "WorkSchedule", action = "http://localhost:80/VTS/WS/WorkSchedule")
    @WebResult(name = "WorkScheduleResult", targetNamespace = "http://www.tourenserver.de/")
    @RequestWrapper(localName = "WorkSchedule", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.WorkSchedule")
    @ResponseWrapper(localName = "WorkScheduleResponse", targetNamespace = "http://www.tourenserver.de/", className = "de.tourenserver.WorkScheduleResponse")
    public int workSchedule(
        @WebParam(name = "FMVTID", targetNamespace = "http://www.tourenserver.de/")
        Integer fmvtid,
        @WebParam(name = "FMExtID", targetNamespace = "http://www.tourenserver.de/")
        String fmExtID,
        @WebParam(name = "StartDate", targetNamespace = "http://www.tourenserver.de/")
        XMLGregorianCalendar startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.tourenserver.de/")
        XMLGregorianCalendar endDate,
        @WebParam(name = "StartTime", targetNamespace = "http://www.tourenserver.de/")
        XMLGregorianCalendar startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://www.tourenserver.de/")
        XMLGregorianCalendar endTime,
        @WebParam(name = "StartLocation", targetNamespace = "http://www.tourenserver.de/")
        Integer startLocation,
        @WebParam(name = "EndLocation", targetNamespace = "http://www.tourenserver.de/")
        Integer endLocation,
        @WebParam(name = "Days", targetNamespace = "http://www.tourenserver.de/")
        String days,
        @WebParam(name = "Type", targetNamespace = "http://www.tourenserver.de/")
        Integer type,
        @WebParam(name = "Info", targetNamespace = "http://www.tourenserver.de/")
        String info,
        @WebParam(name = "Replanning", targetNamespace = "http://www.tourenserver.de/")
        Boolean replanning,
        @WebParam(name = "shift", targetNamespace = "http://www.tourenserver.de/")
        Integer shift,
        @WebParam(name = "SBType", targetNamespace = "http://www.tourenserver.de/")
        Integer sbType);

}
