package com.kairos.shiftplanning.rules;
    dialect "java"
import com.kairos.shiftplanning.domain.*;
import com.kairos.shiftplanning.utils.ShiftPlanningUtility;
import java.util.ArrayList;
import org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder;
global HardMediumSoftLongScoreHolder scoreHolder;


/******WTA rules********/

rule "Maximum Shift Length KP-764"
salience 20
    when
        $shift:ShiftRequestPhase(getInterval()!=null)
        $constraintsPenality: Integer(intValue>0) from ($shift.getEmployee().checkConstraints($shift,1))
    then
        $shift.getEmployee().breakLevelConstraints(scoreHolder,kcontext,1,$constraintsPenality);
end

/******WTA rules Ends****/
