package com.kairos.enums;

/**
 * Created by pavan on 8/3/18.
 */
public enum RuleTemplates {
    MAXIMUM_SHIFT_LENGTH,
    MINIMUM_SHIFT_LENGTH,
    MAXIMUM_NUMBER_OF_CONSECUTIVE_DAYS,
    MINIMUM_REST_AFTER_CONSECUTIVE_DAYS_WORKED,
    MAXIMUM_NIGHT_SHIFTS_LENGTH,
    MINIMUM_NUMBER_OF_CONSECUTIVE_NIGHTS,
    MAXIMUM_NUMBER_OF_CONSECUTIVE_NIGHTS,
    MINIMUM_REST_AFTER_CONSECUTIVE_NIGHTS_WORKED,
    MAXIMUM_NUMBER_OF_WORK_NIGHTS,
    MINIMUM_NUMBER_OF_DAYS_OFF_PER_PERIOD,
    MAXIMUM_AVERAGE_SCHEDULED_TIME_PER_WEEK_WITHIN_AN_INTERVAL,
    MAXIMUM_VETO_PER_PERIOD,
    NUMBER_OF_WEEKEND_SHIFTS_IN_A_PERIOD_COMPARED_TO_AVERAGE,
    CARE_DAYS_CHECK,
    MINIMUM_DAILY_RESTING_TIME,
    MINIMUM_DURATION_BETWEEN_SHIFTS,
    MINIMUM_WEEKLY_REST_PERIOD_FIXED_WEEKS,
    SHORTEST_AND_AVERAGE_DAILY_REST_FIXED_TIMES,
    MAXIMUM_NUMBER_OF_SHIFTS_PER_INTERVAL,
    MAXIMUM_SENIOR_DAYS_PER_YEAR,
    MAXIMUM_TIME_BANK,
    MINIMUM_TIME_BANK,
    BREAKS_IN_SHIFT;


    public static RuleTemplates getByTemplateType(String templateType) {
        for(RuleTemplates r: RuleTemplates.values()) {
            if(r.name().equals(templateType)) {
                return r;
            }
        }
        return null;
    }
}
